DEBUG tests/csapp_tests.c:67: ----- RUNNING: ./tests/csapp_tests  argc=1
DEBUG tests/csapp_tests.c:59: 
----- test_dlopen
DEBUG tests/csapp_tests.c:60: 
----- test_functions
[ERROR] (tests/csapp_tests.c:18: errno: None) Function testtest return 22 for data: hello
[ERROR] (tests/csapp_tests.c:33: errno: None) testtest failed
DEBUG tests/csapp_tests.c:67: ----- RUNNING: ./tests/csapp_tests  argc=1
DEBUG tests/csapp_tests.c:59: 
----- test_dlopen
DEBUG tests/csapp_tests.c:60: 
----- test_functions
[ERROR] (tests/csapp_tests.c:18: errno: None) Function testtest return 22 for data: hello
[ERROR] (tests/csapp_tests.c:33: errno: None) testtest failed
DEBUG tests/csapp_tests.c:67: ----- RUNNING: ./tests/csapp_tests  argc=1
DEBUG tests/csapp_tests.c:59: 
----- test_dlopen
DEBUG tests/csapp_tests.c:60: 
----- test_functions
DEBUG tests/csapp_tests.c:61: 
----- test_failures
DEBUG tests/csapp_tests.c:62: 
----- test_dlclose
